services:
  main:
    build: .
    volumes:
      - .:/opt/rust-boy
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /run/user/1000/pulse/native:/tmp/pulse/native
      - ~/.config/pulse/cookie:/tmp/pulse/cookie:ro
    working_dir: /opt/rust-boy
    environment:
      DISPLAY: unix$DISPLAY
      PULSE_COOKIE: /tmp/pulse/cookie
      PULSE_SERVER: unix:/tmp/pulse/native
    tty: true
